volumes:
  gachit:
services:
  test_env:
    build:
      context: .
    volumes:
      - .:/workspace/gachit
      - gachit:/workspace/gachit/.venv
    command: bash -c ". .venv/bin/activate && \
      rye sync --no-lock && \
      pre-commit run --all-files && \
      pytest -svv --doctest-modules"
    environment:
      - IS_TEST_ENV=1
      - GIT_USER_NAME="test user"
      - GIT_USER_EMAIL="test@gmail.com"
    working_dir: /workspace/gachit
